---
- name: Create .ssh directory for root
  become: true
  file:
    path: /root/.ssh
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Copy deploy key
  become: true
  copy:
    src: root/.ssh/isucon12-final.pem
    dest: /root/.ssh/isucon12-final.pem
    mode: 0600

- name: Clone isucon12-final
  become: true
  git:
    repo: git@github.com:isucon/isucon12-final.git
    dest: /home/isucon/isucon12-final
    clone: true
    force: true
    depth: 1

- name: Change owner of isucon12-final
  become: true
  file:
    path: /home/isucon/isucon12-final
    state: directory
    owner: isucon
    group: isucon
    recurse: true
